name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@master
      with:
        deno-version: v1.x
    - run: deno test
